project:
  type: website
  output-dir: docs
  resources:
    - cursor-swapper.js
    - images/

website:
  title: "Theriogenology Lab"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: professor.qmd
        text: Principal Investigator
      - href: members.qmd
        text: Members
      - href: alumni.qmd
        text: Alumni
      - href: publications.qmd
        text: Publications
      - href: research.qmd
        text: Research
      - href: contact.qmd
        text: Contact

format:
  html:
    css: styles.css
    theme: cosmo
    include-in-header:
      text: |
        <script src="cursor-swapper.js"></script>
    toc: true

